name: CI

on:
  
  push:
    branches: [ "patricia" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install specific version of Databricks CLI
        run: |
              chmod 777 databricks_cli_0.220.0_linux/databricks
              databricks_cli_0.220.0_linux/databricks -v
              cp databricks_cli_0.220.0_linux/databricks .
              ./databricks -v


      - name: deploy
        env:
           DATABRICKS_BUNDLE_ENV: "prod"
           DATABRICKS_TOKEN: "${{ secrets.DATABRICKS_TOKEN}}"
        run : |
             pwd
             ls -lrt        
             ./databricks bundle validate